services:
  mysql:
    image: mysql:8.0
    container_name: maialanches_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maialanches        # igual ao DB_DATABASE do .env
      MYSQL_USER: root          # igual ao DB_USERNAME do .env
      MYSQL_PASSWORD:       # igual ao DB_PASSWORD do .env
    ports:
      - "3306:3306"                    # igual ao DB_PORT do .env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: maialanches_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
